//! Observable pre-guard lines, separated from verdict/state operations.
pub const COLLISION:&str = "safedeps: UNDECIDED - required --ignore-scripts flags could not be placed while preserving command data and how npm reads its options. This command is blocked and no rewritten command was sent. This is not a finding about the packages.";
pub const TYPOSQUATS:&str = r#"(lod[bcdfghjklmnpqrstvwxyz]sh|lodahs|loadsh|lodashh|reacct|exprss|axois|babeel|webpackk|esliint|l0dash|m0ment|4xios|reqeusts|requets|djagno|numppy|panddas|pilliow|tensorfow|scikit-learnn|serde_jsonn|tokioo|reqwestt|clapp|github\.con/|githb\.com/|railss|sinatraa|nokogirri|log4jj|springframewrok|commons-collectionss|newtonsoft\.josn|serilogg|nunittt)"#;
pub const PIPED:&str = r#"safedeps: this command pipes text that reads like an install into a shell (`... | sh`) beside the install it runs. The gate checks the visible install, but it cannot extract a package spec from what is piped, and it cannot tell whether the piped text reads the install's own words, so the command is blocked fail-closed. Run the install and the pipe into the shell as separate commands. If the piped text is itself an install, write it out rather than piping it, so it can be checked."#;
pub const READINGS:&str = r#"safedeps: UNDECIDED, not unsafe — safedeps could not finish reading this command: a scanner step (awk, grep or sed) failed, or the command does not close (an open quote, a heredoc without its terminator). So it could not tell whether the command installs a dependency or what it would install. It is blocked fail-closed, and no finding is claimed. Close the command, or check that `echo x | awk 1` works, then retry."#;
pub const INERT:&[(&str,&str)] = &[
    ("downgrade", r#"pre-guard: could not make every npm install in this command inert in place (one is in a compound command the rewrite did not land in, in a statement whose end it could not find, in a script handed to a shell that it cannot reach, in a heredoc body handed to a shell or piped on, or the text it did not read names npm); lifecycle scripts may run before the effect gate verifies (downgraded to detect-and-rollback)."#),
    ("floor", r#"pre-guard: an npm install in this command has no place where safedeps could read npm keeping --ignore-scripts true (its end could not be found, a -- ends npm's options before it, every place changes what npm reads, or its verb is glued to a } inside a substitution, which the rewrite reads as a character and gives no flag); safedeps put the flag right after each verb it read, where the release put it in a compound command, and at the end of a one-statement command, where the release put it there; lifecycle scripts may run before the effect gate verifies (downgraded to detect-and-rollback)."#),
    ("release", r#"pre-guard: could not place --ignore-scripts by reading an npm install in this command (one is in a script handed to a shell that the rewrite cannot reach, in a heredoc fed to a shell, or in text it could not read); safedeps added the flag only at the end of the command, where the release added it, and could not read where npm keeps it, so lifecycle scripts may run before the effect gate verifies (downgraded to detect-and-rollback)."#),
    ("asked", r#"pre-guard: an npm install in this command sets ignore-scripts false; safedeps put --ignore-scripts after it, where npm reads the last value an option is given, and safedeps itself runs the install's scripts only through the rebuild after the closure verifies."#),
    ("unverified", r#"pre-guard: an npm install in this command holds a word the shell decides at run time (a tilde, a brace, $x, $(...), a glob or another expansion), which can set ignore-scripts, take the next word as its value, or end npm's options; safedeps put --ignore-scripts both right after the verb and after the last argument, and could not read whether npm keeps it true, so the install's scripts may run before the effect gate verifies."#),
    ("unread", r#"pre-guard: text of this command that safedeps did not read as a command holds an npm install verb, or an npm inside a word the shell computes, or a command word or npm's command in it is one the shell computes; safedeps put --ignore-scripts right after each npm install verb in a script word or a piped heredoc body that a blank follows or that ends its line, where v2.17.2 put it, and none elsewhere in that text."#),
];
